export const HISTORY_KEY = 'rollz_history';
export const FAVORITES_KEY = 'rollz_favorites';
export const LANG_KEY = 'rollz_lang';
export const EXPERT_MODE_KEY = 'rollz_expert_mode';
export const MAX_HISTORY = 30;
export const MAX_FAVORITES = 30;
export const RANDOM_ORG = 'https://www.random.org/integers/';
export const DICE_SIDES = [4, 6, 8, 10, 12, 20, 100];
export const APP_VERSION = '2026-04-19-6';
