export const dom = {
  expertCheck: /** @type {HTMLInputElement|null} */ (document.getElementById('expert-check')),
  expertPad: document.getElementById('expert-pad'),
  formulaInputWrap: /** @type {HTMLDivElement} */ (document.getElementById('formula-input-wrap')),
  formulaInput: /** @type {HTMLInputElement} */ (document.getElementById('formula-input')),
  formulaPreview: document.getElementById('formula-preview'),
  clearBtn: document.getElementById('clear-btn'),
  modifierInput: /** @type {HTMLInputElement|null} */ (document.getElementById('modifier-input')),
  modifierIncBtn: document.getElementById('modifier-inc'),
  modifierDecBtn: document.getElementById('modifier-dec'),
  rollBtn: document.getElementById('roll-btn'),
  resultSection: document.getElementById('result-section'),
  resultCard: document.getElementById('result-card'),
  resultFormula: document.getElementById('result-formula'),
  resultBreakdown: document.getElementById('result-breakdown'),
  resultTotalRow: document.getElementById('result-total-row'),
  resultTotalLabel: document.getElementById('result-total-label'),
  resultTotal: document.getElementById('result-total'),
  resultTotalNote: document.getElementById('result-total-note'),
  resultSourceNote: document.getElementById('result-source-note'),
  resultMulti: document.getElementById('result-multi'),
  errorBanner: document.getElementById('error-banner'),
  errorText: document.getElementById('error-text'),
  historyList: document.getElementById('history-list'),
  historyEmpty: document.getElementById('history-empty'),
  clearHistoryBtn: document.getElementById('clear-history-btn'),
  addCategoryBtn: document.getElementById('add-category-btn'),
  favoritesList: document.getElementById('favorites-list'),
  favoritesEmpty: document.getElementById('favorites-empty'),
  favoritesModal: document.getElementById('favorites-modal'),
  favoritesModalForm: document.getElementById('favorites-modal-form'),
  favoritesModalTitle: document.getElementById('favorites-modal-title'),
  favoritesModalMessage: document.getElementById('favorites-modal-message'),
  favoritesModalSummary: document.getElementById('favorites-modal-summary'),
  favoritesModalError: document.getElementById('favorites-modal-error'),
  favoritesModalCategoryField: document.getElementById('favorites-modal-category-field'),
  favoritesModalCategoryLabel: document.getElementById('favorites-modal-category-label'),
  favoritesModalCategorySelect: /** @type {HTMLSelectElement|null} */ (document.getElementById('favorites-modal-category-select')),
  favoritesModalCategoryNameField: document.getElementById('favorites-modal-category-name-field'),
  favoritesModalCategoryNameLabel: document.getElementById('favorites-modal-category-name-label'),
  favoritesModalCategoryNameInput: /** @type {HTMLInputElement|null} */ (document.getElementById('favorites-modal-category-name-input')),
  favoritesModalNameField: document.getElementById('favorites-modal-name-field'),
  favoritesModalNameLabel: document.getElementById('favorites-modal-name-label'),
  favoritesModalNameInput: /** @type {HTMLInputElement|null} */ (document.getElementById('favorites-modal-name-input')),
  favoritesModalLabelField: document.getElementById('favorites-modal-label-field'),
  favoritesModalLabelLabel: document.getElementById('favorites-modal-label-label'),
  favoritesModalLabelInput: /** @type {HTMLInputElement|null} */ (document.getElementById('favorites-modal-label-input')),
  favoritesModalCancelBtn: document.getElementById('favorites-modal-cancel'),
  favoritesModalSubmitBtn: document.getElementById('favorites-modal-submit'),
  favoritesModalCloseBtn: document.getElementById('favorites-modal-close'),
  spinnerOverlay: document.getElementById('spinner-overlay'),
  offlineBadge: document.getElementById('offline-badge'),
  installBtn: document.getElementById('install-btn'),
  advantageCheck: /** @type {HTMLInputElement} */ (document.getElementById('advantage-check')),
  disadvantageCheck: /** @type {HTMLInputElement} */ (document.getElementById('disadvantage-check')),
  successCheck: /** @type {HTMLInputElement} */ (document.getElementById('success-check')),
};

export function isStandaloneMode() {
  return window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone === true;
}
